export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	RESET_POST_DATA: 'RESET_POST_DATA',
	SET_MODAL: 'SET_MODAL',
	HIDE_MODAL: 'HIDE_MODAL',
	SET_POSTS: 'SET_POSTS',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
